/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import java.awt.Insets;
import java.awt.Toolkit;

/**
 *
 * @author GAWANKAR
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form logindone
     */
    public Dashboard() {
      
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newdonor = new javax.swing.JButton();
        searchdonor = new javax.swing.JButton();
        request = new javax.swing.JButton();
        bloodcamp = new javax.swing.JButton();
        benefits = new javax.swing.JButton();
        contactus = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        close1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(360, 180));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(632, 341));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newdonor.setBackground(new java.awt.Color(255, 0, 0));
        newdonor.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        newdonor.setForeground(new java.awt.Color(255, 255, 255));
        newdonor.setText("New Donor");
        newdonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newdonorActionPerformed(evt);
            }
        });
        jPanel1.add(newdonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 160, 139, 67));

        searchdonor.setBackground(new java.awt.Color(255, 0, 0));
        searchdonor.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        searchdonor.setForeground(new java.awt.Color(255, 255, 255));
        searchdonor.setText("Search Donor");
        searchdonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdonorActionPerformed(evt);
            }
        });
        jPanel1.add(searchdonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 160, 141, 67));

        request.setBackground(new java.awt.Color(255, 0, 0));
        request.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        request.setForeground(new java.awt.Color(255, 255, 255));
        request.setText("Make A Request");
        request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestActionPerformed(evt);
            }
        });
        jPanel1.add(request, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 160, -1, 67));

        bloodcamp.setBackground(new java.awt.Color(255, 0, 0));
        bloodcamp.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bloodcamp.setForeground(new java.awt.Color(255, 255, 255));
        bloodcamp.setText("Blood Banks");
        bloodcamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodcampActionPerformed(evt);
            }
        });
        jPanel1.add(bloodcamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 304, 139, 72));

        benefits.setBackground(new java.awt.Color(255, 0, 0));
        benefits.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        benefits.setForeground(new java.awt.Color(255, 255, 255));
        benefits.setText("Benefits");
        benefits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benefitsActionPerformed(evt);
            }
        });
        jPanel1.add(benefits, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 304, 141, 72));

        contactus.setBackground(new java.awt.Color(255, 0, 0));
        contactus.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        contactus.setForeground(new java.awt.Color(255, 255, 255));
        contactus.setText("About Us");
        contactus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactusActionPerformed(evt);
            }
        });
        jPanel1.add(contactus, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 304, 161, 72));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DashBoard");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("DONATION NATION");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 300, -1));

        close1.setBackground(new java.awt.Color(0, 0, 0));
        close1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close1.setForeground(new java.awt.Color(255, 255, 255));
        close1.setText("X");
        close1.setBorder(null);
        close1.setDefaultCapable(false);
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close1ActionPerformed(evt);
            }
        });
        jPanel1.add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 21, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\isran\\Downloads\\DN.jfif")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 700, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close1ActionPerformed
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_close1ActionPerformed

    private void newdonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newdonorActionPerformed
        // TODO add your handling code here:
        Newdonorinfo obj1=new Newdonorinfo();
        obj1.setVisible(true);
        dispose();
    }//GEN-LAST:event_newdonorActionPerformed

    private void searchdonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdonorActionPerformed
        // TODO add your handling code here:
        searchselection ob12=new searchselection();
        ob12.setVisible(true);
        dispose();
    }//GEN-LAST:event_searchdonorActionPerformed

    private void requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestActionPerformed
        // TODO add your handling code here:
      Reciever obj2=new Reciever();
      obj2.setVisible(true);
      dispose();
    }//GEN-LAST:event_requestActionPerformed

    private void bloodcampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodcampActionPerformed
        // TODO add your handling code here:
        bloodcamp ob22=new bloodcamp();
       ob22.setVisible(true);
      dispose();
    }//GEN-LAST:event_bloodcampActionPerformed

    private void benefitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benefitsActionPerformed
        // TODO add your handling code here:
        Benefits obj6=new Benefits();
       obj6.setVisible(true);
      dispose();
    }//GEN-LAST:event_benefitsActionPerformed

    private void contactusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactusActionPerformed
        // TODO add your handling code here:
         Contactus obj9=new Contactus();
       obj9.setVisible(true);
      dispose();
    }//GEN-LAST:event_contactusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton benefits;
    private javax.swing.JButton bloodcamp;
    private javax.swing.JButton close1;
    private javax.swing.JButton contactus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newdonor;
    private javax.swing.JButton request;
    private javax.swing.JButton searchdonor;
    // End of variables declaration//GEN-END:variables
}
