/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.Period;
import java.util.regex.Pattern;
import javax.swing.JTextField;


/**
 *
 * @author GAWANKAR
 */
public class Newdonor extends javax.swing.JFrame {

    /**
     * Creates new form Newdonor
     */
    public Newdonor() {
        initComponents();
    }

    
    void NextCall(String donorno,String fname, String lname, String bloodgrp,String email, String mob, String city, 
            String state, String address,String height,  String sex,String weight, String age,String donate)
    {
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/login","root","123456789"); 
                Statement stmt = conn.createStatement();
                String qrry1 = "Insert into donor values ("
                        + "'" +donorno+ "',"
                        + "'" +fname+ "',"
                        + "'" +lname+ "',"
                        + "'" +bloodgrp+ "',"
                        + "'" +email+ "',"
                        + "'" +mob+ "',"
                        + "'" +city+ "',"
                        + "'" +state+ "',"
                        + "'" +address+ "',"
                        + "'" +height+ "',"
                        + "'" +sex+ "',"
                        + "'" +weight+ "',"
                        + "'" +age+ "',"
                        + "'" +donate+ "');";
                //JOptionPane.showMessageDialog(null,qrry);
                stmt.executeUpdate(qrry1);
                stmt.close();
                conn.close();
        
           JOptionPane.showMessageDialog(null,"SAVED!");
           //new Limit().setVisible(true); 
           Newdonorfinal obj3=new Newdonorfinal();
       obj3.setVisible(true);
      dispose();
    }catch(HeadlessException | ClassNotFoundException | SQLException ex){
    
        JOptionPane.showMessageDialog(null,"Error in connectivity"+ex);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        close3 = new javax.swing.JButton();
        donornolabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        bloodgrouplabel = new javax.swing.JLabel();
        lastnamelabel = new javax.swing.JLabel();
        statelabel = new javax.swing.JLabel();
        mobilenolabel = new javax.swing.JLabel();
        sexlabel = new javax.swing.JLabel();
        firstnamelabel = new javax.swing.JLabel();
        mobilenotext = new javax.swing.JTextField();
        firstnametext = new javax.swing.JTextField();
        heighttext = new javax.swing.JTextField();
        lastnametext = new javax.swing.JTextField();
        sextext = new javax.swing.JComboBox<>();
        statetext = new javax.swing.JTextField();
        donatetext = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        weightlabel = new javax.swing.JLabel();
        donatetypelabel = new javax.swing.JLabel();
        weighttext = new javax.swing.JTextField();
        cm = new javax.swing.JLabel();
        kgs = new javax.swing.JLabel();
        cancel1 = new javax.swing.JButton();
        heightlabel = new javax.swing.JLabel();
        bloodtext = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        emailidlabel = new javax.swing.JLabel();
        emailidtext = new javax.swing.JTextField();
        addresslabel = new javax.swing.JLabel();
        addresstext = new javax.swing.JTextField();
        citylabel = new javax.swing.JLabel();
        citytext = new javax.swing.JTextField();
        donorlabel = new javax.swing.JLabel();
        checkbox = new javax.swing.JCheckBox();
        agelabel1 = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        dobchoose = new com.toedter.calendar.JDateChooser();
        agetext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(360, 0));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Donor");

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Become    a    New    Donor");

        back.setBackground(new java.awt.Color(255, 0, 0));
        back.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.setBorder(null);
        back.setBorderPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        close3.setBackground(new java.awt.Color(255, 0, 0));
        close3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close3.setForeground(new java.awt.Color(255, 255, 255));
        close3.setText("X");
        close3.setBorder(null);
        close3.setDefaultCapable(false);
        close3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back)
                    .addComponent(close3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(24, 24, 24))
        );

        donornolabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        donornolabel.setText("Donor No.");

        agelabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        agelabel.setText("Age");

        bloodgrouplabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bloodgrouplabel.setText("Blood Group");

        lastnamelabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lastnamelabel.setText("Last Name");

        statelabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        statelabel.setText("State");

        mobilenolabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        mobilenolabel.setText("Mobile No.");

        sexlabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        sexlabel.setText("Gender");

        firstnamelabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        firstnamelabel.setText("First Name");

        mobilenotext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mobilenotext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenotextActionPerformed(evt);
            }
        });

        firstnametext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        heighttext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        heighttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heighttextActionPerformed(evt);
            }
        });

        lastnametext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        sextext.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", "Others" }));
        sextext.setBorder(null);
        sextext.setOpaque(false);

        statetext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        statetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statetextActionPerformed(evt);
            }
        });

        donatetext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        donatetext.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blood Donation.", "Plasma Donation.", "Platelet Donation.", "Plasma Antibodies." }));
        donatetext.setBorder(null);
        donatetext.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Minimum weight should be 40");

        next.setBackground(new java.awt.Color(255, 0, 0));
        next.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Save And Next");
        next.setBorderPainted(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        weightlabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        weightlabel.setText("Weight");

        donatetypelabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        donatetypelabel.setText("Donate");

        weighttext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        weighttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weighttextActionPerformed(evt);
            }
        });

        cm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cm.setText("CM");

        kgs.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kgs.setText("KGS");

        cancel1.setBackground(new java.awt.Color(255, 0, 0));
        cancel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cancel1.setForeground(new java.awt.Color(255, 255, 255));
        cancel1.setText("Cancel");
        cancel1.setBorderPainted(false);
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });

        heightlabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        heightlabel.setText("Height");

        bloodtext.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-" }));
        bloodtext.setBorder(null);
        bloodtext.setOpaque(false);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("Age should be between 18-60");

        emailidlabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        emailidlabel.setText("E-mail Id");

        emailidtext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        emailidtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailidtextActionPerformed(evt);
            }
        });

        addresslabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        addresslabel.setText("Address");

        addresstext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addresstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresstextActionPerformed(evt);
            }
        });

        citylabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        citylabel.setText("City");

        citytext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        donorlabel.setBackground(new java.awt.Color(255, 255, 255));
        donorlabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        donorlabel.setForeground(new java.awt.Color(255, 102, 102));
        donorlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));

        checkbox.setBackground(new java.awt.Color(255, 255, 255));
        checkbox.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        checkbox.setForeground(new java.awt.Color(255, 0, 0));
        checkbox.setText("All the above information is true to my knowledge.");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });

        agelabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        agelabel1.setText("DOB");

        calculate.setBackground(new java.awt.Color(51, 51, 51));
        calculate.setFont(new java.awt.Font("Arial Black", 0, 8)); // NOI18N
        calculate.setForeground(new java.awt.Color(255, 255, 255));
        calculate.setText("check elligibility");
        calculate.setBorderPainted(false);
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        dobchoose.setDateFormatString("dd/MM/yyyy");
        dobchoose.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        agetext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        agetext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(firstnamelabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(donornolabel)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstnametext, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(donorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailidlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(citytext, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statetext, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(weighttext, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(kgs))
                                    .addComponent(jLabel10)
                                    .addComponent(emailidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(sexlabel)
                                .addGap(32, 32, 32)
                                .addComponent(sextext, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(lastnamelabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastnametext, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bloodgrouplabel)
                                .addGap(18, 18, 18)
                                .addComponent(bloodtext, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(mobilenolabel)
                                            .addComponent(heightlabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(agelabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(donatetypelabel, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(donatetext, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(heighttext, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(cm))
                                                    .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(mobilenotext, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(20, 20, 20)
                                                        .addComponent(dobchoose, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(calculate)
                                                        .addGap(116, 116, 116)
                                                        .addComponent(agetext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(64, 64, 64))))
                                    .addComponent(checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addresslabel))))))
                .addGap(33, 49, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next)
                    .addComponent(weightlabel)
                    .addComponent(statelabel)
                    .addComponent(citylabel))
                .addGap(140, 140, 140))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(donornolabel)
                                .addComponent(donorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sextext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sexlabel))))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(firstnamelabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(firstnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lastnamelabel)
                                .addComponent(lastnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bloodgrouplabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bloodtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailidlabel)
                                .addComponent(emailidtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobilenolabel)
                            .addComponent(mobilenotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(citylabel)
                            .addComponent(citytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addresslabel)
                            .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statelabel)
                            .addComponent(statetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heightlabel)
                            .addComponent(heighttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cm, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(weightlabel)
                        .addComponent(weighttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kgs, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dobchoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(agelabel)
                                        .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addComponent(agetext, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(agelabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donatetypelabel)
                    .addComponent(donatetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(next)
                    .addComponent(cancel1))
                .addGap(54, 54, 54))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void heighttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heighttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heighttextActionPerformed

    private void statetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statetextActionPerformed

    @SuppressWarnings("empty-statement")
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", emailidtext.getText()))) 
            {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            }
         if( 
                 //donorlabel.getText().length()==0||
                 firstnametext.getText().length()==0||lastnametext.getText().length()==0
                 // ||bloodtext.Jcombi.length==""
                 ||emailidtext.getText().length()==0||mobilenotext.getText().length()==0||
                 citytext.getText().length()==0||statetext.getText().length()==0||addresstext.getText().length()==0
                 ||heighttext.getText().length()==0||
                 //sextext.getSelectedItem().toString==""||
                 weighttext.getText().length()==0||agetext.getText().length()==0)
         {
                JOptionPane.showMessageDialog(null,"All Details Compulsory!");
            }
         else if ((Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", emailidtext.getText())))
            {
                JOptionPane.showMessageDialog(null, "The email is valid", "Good!", JOptionPane.INFORMATION_MESSAGE);
                NextCall(donorlabel.getText(),
                        firstnametext.getText(),lastnametext.getText(),bloodtext.getSelectedItem().toString(),emailidtext.getText(),mobilenotext.getText(),
                 citytext.getText(),statetext.getText(),addresstext.getText(),heighttext.getText(),sextext.getSelectedItem().toString(),weighttext.getText(),agetext.getText(),
                 donatetext.getSelectedItem().toString());
            }
        

    }//GEN-LAST:event_nextActionPerformed

    private void weighttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weighttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weighttextActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
//       setVisible(false);
//       new Newdonorinfo().setVisible(true); 
Newdonorinfo obj3=new Newdonorinfo();
       obj3.setVisible(true);
      dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancel1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
//        setVisible(false);
//        new Newdonorinfo().setVisible(true); 
Newdonorinfo obj4=new Newdonorinfo();
       obj4.setVisible(true);
      dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/login","root","123456789");
           Statement stmt= conn.createStatement();
            ResultSet rs=stmt.executeQuery("select max(donorno) from donor");
            if(rs.next())
            {
                int no=rs.getInt(1);
                no=no+1;
                String str=String.valueOf(no);
                donorlabel.setText(str);
            }
            else
                donorlabel.setText("1");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Newdonor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown

    private void emailidtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailidtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailidtextActionPerformed

    private void close3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close3ActionPerformed
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_close3ActionPerformed

    private void addresstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresstextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addresstextActionPerformed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        // TODO add your handling code here:
        if(checkbox.isSelected()){
            JOptionPane.showMessageDialog(null, "All the information provided above is true to your knowledge.");
            next.setEnabled(true);
        }else{
            next.setEnabled(false);
            JOptionPane.showMessageDialog(null, "please fill all details");
        }
    
    }//GEN-LAST:event_checkboxActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
       String dateofbirth=((JTextField)dobchoose.getDateEditor().getUiComponent()).getText();
       String dob[]=dateofbirth.split("/");
       int day=Integer.parseInt(dob[0]);
       int month=Integer.parseInt(dob[1]);
       int year=Integer.parseInt(dob[2]);
       LocalDate selectedDate=LocalDate.of(year,month,day);
       LocalDate currentDate=LocalDate.now();
       int resultYear=Period.between(selectedDate,currentDate).getYears();
       agetext.setText(""+resultYear);
       
       Period period=Period.between(currentDate,selectedDate);
       System.out.println(period.getYears());
        
       int age=Integer.parseInt(agetext.getText());
       if(age<=18 || age>65){
       
           JOptionPane.showMessageDialog(null, "Not a Valid Age for donation");
            next.setEnabled(true);
       }
           else
       {
           next.setEnabled(false);
            JOptionPane.showMessageDialog(null, "valid age for donation");
       }

// TODO add your handling code here:
    }//GEN-LAST:event_calculateActionPerformed

    private void mobilenotextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenotextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenotextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newdonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newdonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newdonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newdonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newdonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslabel;
    private javax.swing.JTextField addresstext;
    private javax.swing.JLabel agelabel;
    private javax.swing.JLabel agelabel1;
    private javax.swing.JLabel agetext;
    private javax.swing.JButton back;
    private javax.swing.JLabel bloodgrouplabel;
    private javax.swing.JComboBox<String> bloodtext;
    private javax.swing.JButton calculate;
    private javax.swing.JButton cancel1;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JLabel citylabel;
    private javax.swing.JTextField citytext;
    private javax.swing.JButton close3;
    private javax.swing.JLabel cm;
    private com.toedter.calendar.JDateChooser dobchoose;
    private javax.swing.JComboBox<String> donatetext;
    private javax.swing.JLabel donatetypelabel;
    private javax.swing.JLabel donorlabel;
    private javax.swing.JLabel donornolabel;
    private javax.swing.JLabel emailidlabel;
    private javax.swing.JTextField emailidtext;
    private javax.swing.JLabel firstnamelabel;
    private javax.swing.JTextField firstnametext;
    private javax.swing.JLabel heightlabel;
    private javax.swing.JTextField heighttext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kgs;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JTextField lastnametext;
    private javax.swing.JLabel mobilenolabel;
    private javax.swing.JTextField mobilenotext;
    private javax.swing.JButton next;
    private javax.swing.JLabel sexlabel;
    private javax.swing.JComboBox<String> sextext;
    private javax.swing.JLabel statelabel;
    private javax.swing.JTextField statetext;
    private javax.swing.JLabel weightlabel;
    private javax.swing.JTextField weighttext;
    // End of variables declaration//GEN-END:variables

   
}
