/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Pattern;
/**
 *
 * @author GAWANKAR
 */
public class updatedonor extends javax.swing.JFrame {

    /**
     * Creates new form updatedonor
     */
    public updatedonor() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        cross = new javax.swing.JButton();
        donornolabel = new javax.swing.JLabel();
        donornotext = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        firstnamelabel = new javax.swing.JLabel();
        emailidlabel = new javax.swing.JLabel();
        citylabel = new javax.swing.JLabel();
        addresslabel = new javax.swing.JLabel();
        weightlabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        heightlabel = new javax.swing.JLabel();
        lastnamelabel = new javax.swing.JLabel();
        statelabel = new javax.swing.JLabel();
        mobilenolabel = new javax.swing.JLabel();
        firstnametext = new javax.swing.JTextField();
        lastnametext = new javax.swing.JTextField();
        emailidtext = new javax.swing.JTextField();
        statetext = new javax.swing.JTextField();
        agetext = new javax.swing.JTextField();
        heighttext = new javax.swing.JTextField();
        citytext = new javax.swing.JTextField();
        mobilenotext = new javax.swing.JTextField();
        weighttext = new javax.swing.JTextField();
        addresstext = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        update = new javax.swing.JButton();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(340, 130));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPDATE DONOR DETAILS");

        back.setBackground(new java.awt.Color(255, 0, 0));
        back.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.setBorder(null);
        back.setBorderPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        cross.setBackground(new java.awt.Color(255, 0, 0));
        cross.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cross.setForeground(new java.awt.Color(255, 255, 255));
        cross.setText("X");
        cross.setBorder(null);
        cross.setBorderPainted(false);
        cross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crossActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cross, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cross, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        donornolabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        donornolabel.setText("Donor No.");

        donornotext.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        donornotext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));

        firstnamelabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        firstnamelabel.setText("First Name");

        emailidlabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        emailidlabel.setText("Email Id");

        citylabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        citylabel.setText("City");

        addresslabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        addresslabel.setText("Address");

        weightlabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        weightlabel.setText("Weight");

        agelabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        agelabel.setText("Age");

        heightlabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        heightlabel.setText("Height");

        lastnamelabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lastnamelabel.setText("Last Name");

        statelabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        statelabel.setText("State");

        mobilenolabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        mobilenolabel.setText("Mobile No");

        firstnametext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lastnametext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lastnametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnametextActionPerformed(evt);
            }
        });

        emailidtext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        statetext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        agetext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        heighttext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        citytext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        mobilenotext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        weighttext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        addresstext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        reset.setBackground(new java.awt.Color(255, 0, 0));
        reset.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("RESET");
        reset.setBorder(null);
        reset.setBorderPainted(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(255, 0, 0));
        update.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.setBorder(null);
        update.setBorderPainted(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(255, 0, 0));
        search.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("SEARCH");
        search.setBorder(null);
        search.setBorderPainted(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(heightlabel)
                                .addGap(61, 61, 61)
                                .addComponent(heighttext, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addresslabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(emailidlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(firstnamelabel)
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstnametext, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailidtext)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(citylabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(citytext, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(weighttext, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mobilenotext, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statetext, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agetext, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mobilenolabel)
                                    .addComponent(agelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statelabel)
                                    .addComponent(weightlabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lastnamelabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(lastnametext, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(donornolabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(donornotext, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donornotext)
                    .addComponent(donornolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnamelabel)
                    .addComponent(lastnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnamelabel))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agelabel)
                    .addComponent(agetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailidlabel)
                    .addComponent(emailidtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(citylabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(citytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(statelabel)
                        .addComponent(statetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilenolabel)
                    .addComponent(mobilenotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addresslabel)
                    .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightlabel)
                    .addComponent(weighttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heighttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightlabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        //        setVisible(false);
        //        new Newdonorinfo().setVisible(true);
        Newdonorinfo obj4=new Newdonorinfo();
        obj4.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void crossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crossActionPerformed
        System.exit(0);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_crossActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String donorno =donornotext.getText();
        try{

            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/login","root","123456789");
            Statement stmt= conn.createStatement();
            String qrry = ("select * from donor where donorno='"+donorno+"'");
            ResultSet rs= stmt.executeQuery(qrry);

            if(rs.next())
            {
                firstnametext.setText(rs.getString(2));
                lastnametext.setText(rs.getString(3));
                emailidtext.setText(rs.getString(5));
                agetext.setText(rs.getString(13));
                citytext.setText(rs.getString(7));
                statetext.setText(rs.getString(8));
                addresstext.setText(rs.getString(9));
                mobilenotext.setText(rs.getString(6));
                heighttext.setText(rs.getString(10));
                weighttext.setText(rs.getString(12));
                donornotext.setEditable(false);

            }
            else
            JOptionPane.showMessageDialog(null,"Donor Not doesn't Exist");
            //           Newdonorinfo obj5=new Newdonorinfo();
            //       obj5.setVisible(true);
            //      dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in connectivity");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void lastnametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnametextActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        setVisible(false);
        new updatedonor().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String donorno=donornotext.getText();
        String fname=firstnametext.getText();
        String lname=lastnametext.getText();
        String email=emailidtext.getText();
        String age=agetext.getText();
        String city=citytext.getText();
        String state=statetext.getText();
        String address=addresstext.getText();
        String mob=mobilenotext.getText();
        String height=heighttext.getText();
        String weight=weighttext.getText();

        try{
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/login","root","123456789");
            Statement stmt= conn.createStatement();

            if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", emailidtext.getText()))) 
            {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            }
                         else if ((Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", emailidtext.getText())))
            {
                JOptionPane.showMessageDialog(null, "The email is valid", "Good!", JOptionPane.INFORMATION_MESSAGE);
//                NextCall();
                        stmt.executeUpdate ("update donor set fname='"+fname+"',lname='"+lname+"',email='"+email+"',age='"+age+"',"
                + "city='"+city+"',state='"+state+"',address='"+address+"',mob='"+mob+"',height='"+height+"',weight='"+weight+"' where donorno='"+donorno+"'");
                     
                    JOptionPane.showMessageDialog(null,"UPDATED!");
            setVisible(false);
            Newdonorinfo obj5=new Newdonorinfo();
            obj5.setVisible(true);
            dispose();
            
            }

//            stmt.executeUpdate ("update donor set fname='"+fname+"',lname='"+lname+"',email='"+email+"',age='"+age+"',"
//                + "city='"+city+"',state='"+state+"',address='"+address+"',mob='"+mob+"',height='"+height+"',weight='"+weight+"' where donorno='"+donorno+"'");

//            JOptionPane.showMessageDialog(null,"UPDATED!");
//            setVisible(false);
//            Newdonorinfo obj5=new Newdonorinfo();
//            obj5.setVisible(true);
//            dispose();
            

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error in connectivity");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatedonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatedonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatedonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatedonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatedonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslabel;
    private javax.swing.JTextField addresstext;
    private javax.swing.JLabel agelabel;
    private javax.swing.JTextField agetext;
    private javax.swing.JButton back;
    private javax.swing.JLabel citylabel;
    private javax.swing.JTextField citytext;
    private javax.swing.JButton cross;
    private javax.swing.JLabel donornolabel;
    private javax.swing.JTextField donornotext;
    private javax.swing.JLabel emailidlabel;
    private javax.swing.JTextField emailidtext;
    private javax.swing.JLabel firstnamelabel;
    private javax.swing.JTextField firstnametext;
    private javax.swing.JLabel heightlabel;
    private javax.swing.JTextField heighttext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JTextField lastnametext;
    private javax.swing.JLabel mobilenolabel;
    private javax.swing.JTextField mobilenotext;
    private javax.swing.JButton reset;
    private javax.swing.JButton search;
    private javax.swing.JLabel statelabel;
    private javax.swing.JTextField statetext;
    private javax.swing.JButton update;
    private javax.swing.JLabel weightlabel;
    private javax.swing.JTextField weighttext;
    // End of variables declaration//GEN-END:variables
}
